class TrainParam:
    def __init__(self,message_length =64,
        resolution = 256,
        lr_enc = 1e-4,
        lr_dec = 1e-4,
        use_schdule = False,
        batchsize = 64,
        decoder_loss = 1.0,
        encoder_loss = 1.0,
        adversarial_loss = 1.0,
        vgg_loss = 1.0,
        lpips_loss = 1.0,
        split_batches = True,
        amp = False,
        fp16 = False,
        datapath = "/public/wangguanjie/data/10k/",
        epochs = 400,
        save_step = 10,
        use_part_dataset = 0,
        dataset = "MSCOCO",
        scaling_i = 1.0,
        scaling_w = 0.5,
        if_continue=False,
        reload_path="",
        use_dis = False,
        **args):
        self.message_length =message_length
        self.resolution = resolution
        self.lr_enc = lr_enc
        self.lr_dec = lr_dec
        self.use_schdule = use_schdule
        self.batchsize = batchsize
        self.decoder_loss = decoder_loss
        self.encoder_loss = encoder_loss
        self.adversarial_loss = adversarial_loss
        self.vgg_loss = vgg_loss
        self.lpips_loss =lpips_loss
        self.split_batches = split_batches
        self.amp = amp
        self.fp16 = fp16
        self.datapath = datapath
        self.epochs = epochs
        self.dataset = dataset
        self.save_step = save_step
        self.use_part_dataset = use_part_dataset
        self.use_dis = use_dis
        self.scaling_i = scaling_i
        self.scaling_w = scaling_w
        self.if_continue = if_continue
        self.reload_path = reload_path